name: python3-dl  # default is root
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:  # will be installed by conda
  - python>=3.7
  - pytorch>=1.0.0
  - torchvision=0.2.2
  - numpy>=1.16
  - nltk>=3.4
  - tensorboardx>=1.6
  - pip
  - pip:  # will be installed by pip
    - torchtext>=0.3.1<0.4.0
